### ISSUE TITLE
Existing integration test failures

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/infrastructure-integration-test#38]
```
rspec ./spec/features/create_object_no_files_spec.rb:17 # Use Argo to create an object without any files is expected to text "Register DOR Items"
rspec ./spec/features/create_collection_spec.rb:18 # Use Argo to create a collection is expected to eq "adminPolicy"
rspec ./spec/features/reaccession_via_preassembly_spec.rb:21 # Reaccession from preassembly is expected to text "Success! Your job is queued. A link to job output will be emailed to you upon completion."
rspec ./spec/features/sdr_deposit_spec.rb:15 # SDR deposit deposits objects
```

**Comment by jcoyne** [comment]
I'm not able to duplicate these failures.

**Comment by jcoyne** [comment]
The `spec/features/create_collection_spec.rb` is resolve after deploying sul-dlss/dor-services-app#751

**Comment by aaron-collier** [comment]
Now I'm only getting 1:

```
  1) SDR deposit deposits objects
     Failure/Error:
       result = SdrClient::Deposit.run(apo: apo,
                                       source_id: source_id,
                                       collection: collection,
                                       catkey: catkey,
                                       url: api_url,
                                       files: ['Gemfile', 'Gemfile.lock'])

     RuntimeError:
       There was an error with your request: {"id":"bad_request","message":"#/components/schemas/RequestFile missing required parameters: version"}
     # /Users/sul.amcollie/.rvm/gems/ruby-2.5.4/gems/sdr-client-0.16.1/lib/sdr_client/deposit/process.rb:65:in `unexpected_response'
     # /Users/sul.amcollie/.rvm/gems/ruby-2.5.4/gems/sdr-client-0.16.1/lib/sdr_client/deposit/process.rb:57:in `upload_metadata'
     # /Users/sul.amcollie/.rvm/gems/ruby-2.5.4/gems/sdr-client-0.16.1/lib/sdr_client/deposit/process.rb:38:in `run'
     # /Users/sul.amcollie/.rvm/gems/ruby-2.5.4/gems/sdr-client-0.16.1/lib/sdr_client/deposit.rb:45:in `run'
     # ./spec/features/sdr_deposit_spec.rb:21:in `block (2 levels) in <top (required)>'
```

**Comment by aaron-collier** [comment]
I suspect this is running against current deployments. So I'm going to close and see what happens when things have calmed down.
